name: ci

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-unit-tests:
    # Name the Job
    name: Run unit tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: NPM install
        run: npm install

      - name: NPM run tests
        run: npm run test

      - name: Get code coverage
        run: |
          # Set the BRANCH_NAME to use as the badge file name later
          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
          
          # Get the code coverage, set as Github env var
          COVERAGE=$(python3 -c "import json;print(json.load(open('coverage/coverage-summary.json'))['total']['lines']['pct'])", end='')
          echo "COVERAGE=$(echo ${COVERAGE})" >> $GITHUB_ENV

      - name: Create code coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1708995a4933a08f4838df0243926653
          filename: cilly__${{ env.BRANCH }}.json
          label: coverage
          labelColor: "#24292E"  # Dark grey
          message: ${{ env.COVERAGE }}%
          color: "#34D058"  # Green
          namedLogo: mocha
          logoColor: "#959DA5"  # Grey

